---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  labels:
    name: autoscaler
    app: autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-rb
  labels:
    app: autoscaler
    name: autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoscaler-cr
subjects:
- kind: ServiceAccount
  name: autoscaler-sa 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-cr
  labels:
    app: autoscaler
    name: autoscaler
rules:
  - apiGroups: ["","metrics"]
    resources: ["nodes", "pods", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: 
    - "run.tanzu.vmware.com"
    resources: 
    - "tanzukubernetesclusters"
    verbs: ["get", "list", "watch", "patch"]
