apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: autoscaler-dev
    app: autoscaler-dev
  name: autoscaler-dev-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: autoscaler-dev
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: autoscaler-dev
        version: v1
    spec:
      containers:
      - env:
        - name: INCLUSTER_CONFIG
          value: "1"
        - name: NAMESPACE
          value: dev
        - name: SCRIPT_FREQ_MIN
          value: "1"
        - name: EXCLUDE_CLUSTERS
          value: "(cluster1 cluster2)"
        - name: MAX_NODE_COUNT
          value: "3"
        - name: MIN_NODE_COUNT
          value: "1"
        - name: MIN_AVAIL_MEM_PERCENTAGE
          value: "30"
        - name: MIN_AVAIL_CPU_PERCENTAGE
          value: "20"
        image: accordingtoalinahid/autoscaler:0.0.4
        imagePullPolicy: Always
        name: autoscaler-dev
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 9999
        volumeMounts:
        - mountPath: /user/autoscaler
          name: cache-volume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        stdin: true
        tty: true
      volumes:
      - name: cache-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: autoscaler-sa
      serviceAccountName: autoscaler-sa
      terminationGracePeriodSeconds: 30
